modLoader="kotlinforforge"
loaderVersion="[1,)"
license="MIT"
[[mods]]
modId="techmod"
version="${version}"
displayName="Tech Mod"
logoFile="icon.png"
authors="Arcanox"
description='''
TODO: This is a placeholder description for this mod!
'''
[[dependencies.techmod]]
    modId="forge"
    mandatory=true
    versionRange="[34.1.25,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.techmod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.3,)"
    ordering="NONE"
    side="BOTH"
